# Generated by Django 3.2.4 on 2021-06-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_alter_transacciones_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacciones',
            new_name='LibroDiario',
        ),
        migrations.AlterModelTable(
            name='librodiario',
            table='libroDiario',
        ),
    ]
