# Generated by Django 3.2.4 on 2021-06-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_auto_20210605_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('iva_total', models.IntegerField()),
                ('total_v', models.IntegerField()),
            ],
            options={
                'db_table': 'Boleta',
            },
        ),
        migrations.CreateModel(
            name='boletaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_actual', models.IntegerField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.boleta')),
            ],
            options={
                'db_table': 'boletaDetalle',
            },
        ),
    ]
