# Generated by Django 3.2.4 on 2021-06-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_boleta_boletadetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
