# Generated by Django 3.2.4 on 2021-06-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0006_alter_boleta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
