# Generated by Django 3.2.4 on 2021-06-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0008_alter_boletadetalle_id_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='librodiario',
            name='metodo_pago',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
