# Generated by Django 3.2.4 on 2021-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0009_librodiario_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librodiario',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='boleta',
            name='metodo_pago',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
