# Generated by Django 3.2.4 on 2021-06-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0010_auto_20210623_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='neto_v',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='iva_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total_v',
            field=models.IntegerField(default=0),
        ),
    ]
