# Generated by Django 3.2.4 on 2021-06-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0011_auto_20210623_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='neto_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boletadetalle',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boletadetalle',
            name='precio_actual',
            field=models.IntegerField(default=0),
        ),
    ]
